/**
 * Static site generator — reads all content from D1 and returns
 * a map of filepath → content to be committed to GitHub.
 */

import type {
  GameRow, GameSettingRow, GameAssetRow, SiteConfigRow,
  DesignTokenRow, FooterLinkRow, BodyArtRow,
} from "../types.js";
import { gameTemplates } from "./registry.js";

export interface GenerateResult {
  files: Map<string, string>;
  hash: string;
}

export async function generateSite(db: D1Database): Promise<GenerateResult> {
  // ── Load all content ──
  const [configRows, gamesRows, tokensRows, linksRows, artRows] = await Promise.all([
    db.prepare("SELECT * FROM site_config").all<SiteConfigRow>(),
    db.prepare("SELECT * FROM games ORDER BY sort_order").all<GameRow>(),
    db.prepare("SELECT * FROM design_tokens ORDER BY category, id").all<DesignTokenRow>(),
    db.prepare("SELECT * FROM footer_links ORDER BY group_name, sort_order").all<FooterLinkRow>(),
    db.prepare("SELECT * FROM body_art").all<BodyArtRow>(),
  ]);

  const config: Record<string, string> = {};
  for (const row of configRows.results) config[row.key] = row.value;

  const games = gamesRows.results;
  const tokens = tokensRows.results;
  const storeLinks = linksRows.results.filter((l) => l.group_name === "store");
  const socialLinks = linksRows.results.filter((l) => l.group_name === "social");
  const bodyArt = artRows.results;
  const files = new Map<string, string>();

  // Load settings and assets for each game
  const gameData: Map<number, { settings: Record<string, unknown>; assets: GameAssetRow[] }> = new Map();
  for (const game of games) {
    const [settingsRes, assetsRes] = await Promise.all([
      db.prepare("SELECT * FROM game_settings WHERE game_id = ?").bind(game.id).all<GameSettingRow>(),
      db.prepare("SELECT * FROM game_assets WHERE game_id = ? ORDER BY sort_order").bind(game.id).all<GameAssetRow>(),
    ]);
    const settings: Record<string, unknown> = {};
    for (const s of settingsRes.results) {
      try { settings[s.setting_key] = JSON.parse(s.setting_value); } catch { settings[s.setting_key] = s.setting_value; }
    }
    gameData.set(game.id, { settings, assets: assetsRes.results });
  }

  // ── Generate tokens.css ──
  files.set("css/tokens.css", generateTokensCss(tokens));

  // ── Generate footer.js ──
  files.set("footer.js", generateFooterJs(storeLinks, socialLinks));

  // ── Generate homepage ──
  const homeArt = {
    left: bodyArt.find((a) => a.page_ref === "home" && a.position === "left"),
    right: bodyArt.find((a) => a.page_ref === "home" && a.position === "right"),
  };
  files.set("index.html", generateHomepage(config, games, homeArt));

  // ── Generate each game page ──
  for (const game of games) {
    if (game.status !== "available") continue;
    const data = gameData.get(game.id)!;
    const gameArt = {
      left: bodyArt.find((a) => a.page_ref === game.slug && a.position === "left"),
      right: bodyArt.find((a) => a.page_ref === game.slug && a.position === "right"),
    };
    files.set(`games/${game.slug}/index.html`, generateGamePage(config, game, data.settings, data.assets, gameArt));
  }

  // Compute a simple hash for change tracking
  const hash = await computeHash(JSON.stringify({ config, games, tokens, storeLinks, socialLinks, bodyArt }));

  return { files, hash };
}

// ── Template generators ──

function generateTokensCss(tokens: DesignTokenRow[]): string {
  const fontFace = `@font-face {
\tfont-family: "Advantage";
\tsrc: url("../fonts/Advantage-Regular.woff2") format("woff2");
\tfont-weight: 400;
\tfont-style: normal;
\tfont-display: swap;
}\n`;

  const vars = tokens.map((t) => `\t--${t.token_name}: ${t.token_value};`).join("\n");
  const fontUi = `\t--font-ui:\n\t\tAvenir Next, Avenir, Montserrat, Corbel, Trebuchet MS, Segoe UI, system-ui,\n\t\tsans-serif;`;

  return `/*\n  Design tokens for Eva Games.\n  Generated by Goddess's Dashboard.\n*/\n\n${fontFace}\n:root {\n\tcolor-scheme: light;\n\n${vars}\n\n\t/* Typography */\n${fontUi}\n}\n`;
}

function generateFooterJs(storeLinks: FooterLinkRow[], socialLinks: FooterLinkRow[]): string {
  const formatLinks = (links: FooterLinkRow[]) =>
    links.map((l) => `\t{\n\t\tlabel: ${JSON.stringify(l.label)},\n\t\thref: ${JSON.stringify(l.url)},\n\t\ticon: ${JSON.stringify(l.icon_filename)},\n\t\textraClass: ${JSON.stringify(l.extra_css_class || "")},\n\t}`).join(",\n");

  return `const footerStoreLinks = [\n${formatLinks(storeLinks)},\n];\n\nconst footerSocialLinks = [\n${formatLinks(socialLinks)},\n];\n\n` +
    FOOTER_COMPONENT_CODE;
}

function generateHomepage(
  config: Record<string, string>,
  games: GameRow[],
  art: { left?: BodyArtRow; right?: BodyArtRow },
): string {
  const title = config.site_title || "Eva Games | Eva de Vil";
  const desc = config.meta_description || "";
  const canonical = config.canonical_url || "https://evagames.org/";
  const brandText = config.brand_text || "Eva Games";
  const brandLink = config.brand_link || "https://evagames.org/";
  const themeColor = config.theme_color || "#FFE0F6";

  const gameTiles = games.map((g) => {
    const cssClass = ["game-tile"];
    if (g.status === "available") cssClass.push("game-tile-available");
    if (g.tile_css_class) cssClass.push(g.tile_css_class);
    if (g.status !== "available") cssClass.push("empty");

    const inner = g.status === "available"
      ? `<span class="tile-number">${esc(g.tile_number)}</span>\n              <h2><a class="game-card-link" href="games/${esc(g.slug)}/">${esc(g.title)}</a></h2>\n              <span class="status">${esc(g.status_label)}</span>`
      : `<span class="tile-number">${esc(g.tile_number)}</span>\n              <h2>${esc(g.title)}</h2>\n              <span class="status">${esc(g.status_label)}</span>`;

    return `            <article class="${cssClass.join(" ")}">\n              ${inner}\n            </article>`;
  }).join("\n\n");

  const leftArt = art.left ? `assets/${art.left.image_filename}` : "assets/body-left.png";
  const rightArt = art.right ? `assets/${art.right.image_filename}` : "assets/body-right.png";

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${esc(title)}</title>
    <meta name="description" content="${esc(desc)}" />
    <link rel="canonical" href="${esc(canonical)}" />
    <meta property="og:title" content="${esc(config.og_title || title)}" />
    <meta property="og:description" content="${esc(config.og_description || desc)}" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="${esc(canonical)}" />
    <meta name="theme-color" content="${esc(themeColor)}" />
    <link rel="icon" href="favicon.ico" sizes="48x48" />
    <link rel="icon" href="favicon-192.png" sizes="192x192" type="image/png" />
    <link rel="apple-touch-icon" href="favicon-192.png" />
    <link rel="stylesheet" href="css/tokens.css" />
    <link rel="stylesheet" href="css/base.css" />
    <link rel="stylesheet" href="css/footer.css" />
    <link rel="stylesheet" href="css/home.css" />
    <script src="footer.js" defer></script>
  </head>
  <body>
    <a class="skip-link" href="#games">Skip to games</a>

    <div class="page-shell">
      <header class="site-header" aria-label="Site header">
        <a class="brand-mark" href="${esc(brandLink)}" aria-current="page">
          ${esc(brandText)}
        </a>
      </header>

      <main id="games" class="games-section">
        <h1 class="sr-only">${esc(brandText)}</h1>

        <div class="games-layout">
          <img class="body-art body-art-left" src="${esc(leftArt)}" alt="" aria-hidden="true" />

          <div class="game-grid" aria-label="Game launcher">
${gameTiles}
          </div>

          <img class="body-art body-art-right" src="${esc(rightArt)}" alt="" aria-hidden="true" />
        </div>
      </main>

      <eva-footer></eva-footer>
    </div>
  </body>
</html>
`;
}

function generateGamePage(
  config: Record<string, string>,
  game: GameRow,
  settings: Record<string, unknown>,
  assets: GameAssetRow[],
  art: { left?: BodyArtRow; right?: BodyArtRow },
): string {
  const template = gameTemplates[game.template_id];
  if (!template) return `<!-- Unknown template: ${game.template_id} -->`;

  const title = `${game.title} | ${config.site_title || "Eva Games"}`;
  const themeColor = config.theme_color || "#FFE0F6";

  // Serialize game config for the JS to consume
  const gameConfig = JSON.stringify({ ...settings, assets: assets.map((a) => ({ slot: a.slot_key, file: a.filename, order: a.sort_order })) });

  const leftArt = art.left ? `assets/${art.left.image_filename}` : "assets/body-left.png";
  const rightArt = art.right ? `assets/${art.right.image_filename}` : "assets/body-right.png";

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${esc(title)}</title>
    <meta name="description" content="Play ${esc(game.title)} on Eva Games." />
    <link rel="canonical" href="${esc(config.canonical_url || "https://evagames.org/")}games/${esc(game.slug)}/" />
    <meta property="og:title" content="${esc(title)}" />
    <meta property="og:description" content="Play ${esc(game.title)} on Eva Games." />
    <meta property="og:type" content="website" />
    <meta name="theme-color" content="${esc(themeColor)}" />
    <link rel="icon" href="../../favicon.ico" sizes="48x48" />
    <link rel="icon" href="../../favicon-192.png" sizes="192x192" type="image/png" />
    <link rel="apple-touch-icon" href="../../favicon-192.png" />
    <link rel="stylesheet" href="../../css/tokens.css" />
    <link rel="stylesheet" href="../../css/base.css" />
    <link rel="stylesheet" href="../../css/footer.css" />
    <link rel="stylesheet" href="../../css/game.css" />
    <link rel="stylesheet" href="styles.css" />
    <script>window.__GAME_CONFIG__ = ${gameConfig};</script>
    <script src="../../footer.js" defer></script>
    <script src="game.js" defer></script>
  </head>
  <body>
    <a class="skip-link" href="#game-board">Skip to game</a>

    <div class="page-shell">
      <header class="site-header" aria-label="Site header">
        <a class="brand-mark" href="../../">${esc(config.brand_text || "Eva Games")}</a>
      </header>

      <main class="game-main" aria-labelledby="game-title">
        <div class="game-layout">
          <img class="game-body-art game-body-art-left" src="${esc(leftArt)}" alt="" aria-hidden="true" />
          <section class="game-stage" id="game-stage">
            <div class="game-copy">
              <h1 id="game-title">${esc(game.title)}</h1>
              <p id="game-instructions" class="game-instructions">${esc(String(settings.instructions || ""))}</p>
            </div>
            <div id="game-container"></div>
          </section>
          <img class="game-body-art game-body-art-right" src="${esc(rightArt)}" alt="" aria-hidden="true" />
        </div>
      </main>

      <eva-footer asset-prefix="../../assets/"></eva-footer>
    </div>
  </body>
</html>
`;
}

// ── Helpers ──

function esc(str: string): string {
  return str.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}


async function computeHash(data: string): Promise<string> {
  const encoded = new TextEncoder().encode(data);
  const hashBuffer = await crypto.subtle.digest("SHA-256", encoded);
  return Array.from(new Uint8Array(hashBuffer)).map((b) => b.toString(16).padStart(2, "0")).join("");
}

// The footer web component code (copied as-is for the generated site)
const FOOTER_COMPONENT_CODE = `
function appendTextElement(parent, tagName, className, text) {
\tconst element = document.createElement(tagName);
\telement.className = className;
\telement.textContent = text;
\tparent.append(element);
\treturn element;
}

function createFooterLink({ href, label, icon, extraClass = "" }, kind, assetPrefix) {
\tconst link = document.createElement("a");
\tlink.className = ["footer-link", "footer-link-" + kind, extraClass].filter(Boolean).join(" ");
\tlink.href = href;
\tlink.target = "_blank";
\tlink.rel = "noopener noreferrer";
\tlink.setAttribute("aria-label", label);
\tconst image = document.createElement("img");
\timage.className = "footer-icon";
\timage.src = assetPrefix + icon;
\timage.alt = "";
\timage.setAttribute("aria-hidden", "true");
\tlink.append(image);
\treturn link;
}

class EvaFooter extends HTMLElement {
\tconnectedCallback() {
\t\tif (this.dataset.ready) return;
\t\tconst assetPrefix = this.getAttribute("asset-prefix") || "assets/";
\t\tconst footer = document.createElement("footer");
\t\tfooter.className = "site-footer";
\t\tconst identity = document.createElement("div");
\t\tidentity.className = "footer-identity";
\t\tconst copyright = appendTextElement(identity, "span", "footer-copyright", "\\u00A9");
\t\tcopyright.setAttribute("aria-label", "Copyright");
\t\tconst brandLockup = document.createElement("div");
\t\tbrandLockup.className = "footer-brand-lockup";
\t\tconst brand = appendTextElement(brandLockup, "a", "footer-brand", "Eva de Vil");
\t\tbrand.href = "https://evadevil.com/";
\t\tbrand.rel = "noopener";
\t\tbrand.setAttribute("aria-label", "Visit Eva de Vil main site");
\t\tappendTextElement(brandLockup, "span", "footer-year", new Date().getFullYear().toString());
\t\tidentity.append(brandLockup);
\t\tconst nav = document.createElement("nav");
\t\tnav.className = "footer-links";
\t\tnav.setAttribute("aria-label", "Eva de Vil links");
\t\tconst stores = document.createElement("div");
\t\tstores.className = "footer-link-group";
\t\tstores.setAttribute("aria-label", "Creator stores");
\t\tfooterStoreLinks.forEach((l) => stores.append(createFooterLink(l, "adult", assetPrefix)));
\t\tconst socials = document.createElement("div");
\t\tsocials.className = "footer-link-group footer-link-group-social";
\t\tsocials.setAttribute("aria-label", "Social profiles");
\t\tfooterSocialLinks.forEach((l) => socials.append(createFooterLink(l, "social", assetPrefix)));
\t\tnav.append(stores, socials);
\t\tfooter.append(identity, nav);
\t\tthis.dataset.ready = "true";
\t\tthis.replaceChildren(footer);
\t}
}

customElements.define("eva-footer", EvaFooter);
`;
