import type { GameTemplate } from "../../types.js";

export const template2048: GameTemplate = {
	id: "2048",
	name: "2048",
	version: "1.0.0",
	description:
		"Sliding tile puzzle — merge matching tiles to reach the target value.",
	settings: [
		// ── Simple settings (visible by default) ──
		{
			key: "instructions",
			label: "Instructions",
			description: "Help text shown above the game board.",
			type: "textarea",
			default:
				"Slide the room with arrow keys, WASD, or a swipe. Matching tiles merge. Reach 2048 and the game ends.",
			advanced: false,
			group: "copy",
		},
		{
			key: "win_message",
			label: "Win message",
			description: "Title shown when the player wins.",
			type: "text",
			default: "2048",
			advanced: false,
			group: "copy",
		},
		{
			key: "win_copy",
			label: "Win copy",
			description: "Body text shown when the player wins.",
			type: "text",
			default: "The room is complete.",
			advanced: false,
			group: "copy",
		},
		{
			key: "lose_message",
			label: "Lose message",
			description: "Title shown when no moves remain.",
			type: "text",
			default: "Game over",
			advanced: false,
			group: "copy",
		},
		{
			key: "lose_copy",
			label: "Lose copy",
			description: "Body text shown when no moves remain.",
			type: "text",
			default: "No more moves.",
			advanced: false,
			group: "copy",
		},
		{
			key: "bg_toggle_default",
			label: "Background on by default",
			description: "Whether the GIF background is enabled when the page loads.",
			type: "boolean",
			default: true,
			advanced: false,
			group: "visuals",
		},

		// ── Advanced settings ──
		{
			key: "board_size",
			label: "Board size",
			description: "Number of rows and columns (e.g. 4 for a 4×4 grid).",
			type: "number",
			default: 4,
			validation: { min: 3, max: 8, required: true },
			advanced: true,
			group: "gameplay",
		},
		{
			key: "win_value",
			label: "Win value",
			description: "Tile value the player must reach to win.",
			type: "number",
			default: 2048,
			validation: { min: 16, required: true },
			advanced: true,
			group: "gameplay",
		},
		{
			key: "four_spawn_chance",
			label: "4-tile spawn chance",
			description: "Probability (0–1) that a new tile is 4 instead of 2.",
			type: "number",
			default: 0.1,
			validation: { min: 0, max: 1 },
			advanced: true,
			group: "gameplay",
		},
		{
			key: "move_duration_ms",
			label: "Move animation (ms)",
			description: "Duration of tile slide animation in milliseconds.",
			type: "number",
			default: 150,
			validation: { min: 0, max: 1000 },
			advanced: true,
			group: "timing",
		},
	],
	assetSlots: [
		{
			key: "tile_gif",
			label: "Tile images",
			description:
				"GIF or image for each tile value (2, 4, 8, … 2048). Name files by value, e.g. 2.gif, 4.gif.",
			accept: "image/gif,image/png,image/jpeg,image/webp",
			cropAspectRatio: 1,
			required: false,
			multiple: true,
		},
	],
};
